# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: guhenriq <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2025/05/08 15:41:53 by guhenriq          #+#    #+#              #
#    Updated: 2025/05/08 15:41:53 by guhenriq         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

CC = cc
CFLAGS = -Wall -Wextra -Werror -I../includes
RM = rm -rf
NAME = libft.a

SRCS = \
	ft_atoi.c ft_memset.c ft_strlcpy.c \
	ft_bzero.c ft_putchar_fd.c ft_strlen.c \
	ft_calloc.c ft_putendl_fd.c ft_strmapi.c \
	ft_isalnum.c ft_putnbr_fd.c ft_strncmp.c \
	ft_isalpha.c ft_putstr_fd.c ft_strnstr.c \
	ft_isascii.c ft_split.c ft_strrchr.c \
	ft_isdigit.c ft_strchr.c ft_strtrim.c \
	ft_isprint.c ft_memchr.c ft_strdup.c ft_substr.c \
	ft_itoa.c ft_memcmp.c ft_striteri.c ft_tolower.c \
	ft_memcpy.c ft_strjoin.c ft_toupper.c \
	ft_memmove.c ft_strlcat.c

LIB_OBJS =  $(LIB_SRCS:.c=.o)

all: $(NAME)

$(NAME): $(LIB_OBJS)
	ar rc $(NAME) $(LIB_OBJS)
clean:
	$(RM) $(LIB_OBJS) 
fclean: clean
	$(RM) $(NAME)
re: fclean all

.SILENT: